### ISSUE TITLE
Anh đang thấy em sử dụng if else để chia ra làm các trường hợp chứ a ko thấy OOP đâu cả :))

### ISSUE THREAD

**Issue by GuardianOfGods** [phandung11/java#10]
https://github.com/phandung11/java/blob/0868431eb11c4db4a87f56184905f62448a94519/btvn_buoi6/BattleField/src/battlefield/BattleField.java#L1-L111

**Comment by phandung11** [comment]
e chưa hiểu oop lắm :)

**Comment by GuardianOfGods** [comment]
Có gì đến buổi nào học thì a nói. Giờ nhiều bạn cũng thắc mắc giống e
