### ISSUE TITLE
Bài 2: 2 điểm. Không viết được đầy đủ hàm, phần tìm số nhỏ nhất và chèn chưa làm được.

### ISSUE THREAD

**Issue by GuardianOfGods** [phandung11/java#7]
https://github.com/phandung11/java/blob/311197adb61b80242134338ad87f184b7344af09/kiemtrathang1/bai_2/src/bai_2/Bai_2.java#L1-L48

**Comment by phandung11** [comment]
anh ơi
vì mảng đc sắp xếp giảm dần nên số nhỏ nhất ở cuối
vì vậy e chỉ cần thêm x vào cuối mảng thôi
anh xem xét lại giúp e vs

**Comment by GuardianOfGods** [comment]
Ok + 1 điểm

**Comment by GuardianOfGods** [comment]
Điểm xem ở đây
https://docs.google.com/spreadsheets/d/1LR-E4M0cOVgdXjB43Dm4BQAKeBaVLOAaJU6N48iUHV4/edit?ts=5d9f5fa9#gid=0
